version: "3.5"
services:
  https.dnp.dappnode.eth:
    build: .
    image: "https.dnp.dappnode.eth:0.1.0"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      STAGE: production
      CERTAPI_URL: "ns.dappnode.io:5000"
      LOCAL_PROXYING: "true"
      PUBLIC_DOMAIN: null
      FORCE: null
    networks:
      dncore_network:
        aliases:
          - https.dappnode
    volumes:
      - "portal-certs:/var/lib/https-portal/"
      - "portal-data:/var/run/domains.d/"
volumes:
  portal-certs: {}
  portal-data: {}
networks:
  dncore_network:
    name: dncore_network
    external: true
